In [8]:
delimiter = [";",',','.']
text="我以为, 要是唱得用心良苦, 你总会对我多点在乎. 我以为, 虽然爱情已成往事. "
texts=[text]
for delim in delimiter:
  tmp=[]
  for text in texts:
    tmp.extend(text.split(delim))
  texts = tmp
texts=filter(lambda x:bool(x),map(lambda x: x.strip(),texts))
# texts = [text.strip() for text in texts if len(text.strip())>0]
print(list(texts))

['我以为', '要是唱得用心良苦', '你总会对我多点在乎', '我以为', '虽然爱情已成往事']


In [9]:
import jieba.posseg as pseg

In [10]:
?pseg.cut

Signature: pseg.cut(sentence, HMM=True)
Docstring:
Global `cut` function that supports parallel processing.

Note that this only works using dt, custom POSTokenizer
instances are not supported.
File:      /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/jieba/posseg/__init__.py
Type:      function


In [11]:
a={"a":1}
a.a

AttributeError: 'dict' object has no attribute 'a'

In [30]:
class AttrDict(dict):
    __slots__=()
    __getattr__=dict.__getitem__
    __setattr__=dict.__setitem__

d=AttrDict(a=1,b=2,c=3)
d.a

In [31]:
norm_d=dict(a=1,b=2,c=3)

In [22]:
norm_d.__dict__

AttributeError: 'dict' object has no attribute '__dict__'

In [38]:
def combine(word_list, window = 3): # 我感觉写得有些问题呀, window=2, 实际上只是相邻的词, 我觉得window=2字面上应该是有2对吧.
    if window < 2: window = 2
    for x in range(1, window): # xrange其实是为了兼容性, 就是range
        if x >= len(word_list):
            break
        word_list2 = word_list[x:] # 这个很奇怪啊, 难道不是左边, 右边么?
        res = zip(word_list, word_list2) # 长度不同啊, 
        for r in res:
            yield r

In [41]:
l=['施剑翘', '杀', '孙传芳', '案', '看', '伦常', '礼法', '舆论', '司法', '影响']
list(combine(l,2))

In [42]:
import networkx as nx

In [45]:
fnm=nx.from_numpy_matrix(np.array([[1,1,0],[0,1,1],[0,0,0]]))

In [46]:
fnm

In [47]:
norm_d.items()

dict_items([('a', 1), ('b', 2), ('c', 3)])

In [49]:
l=[1,2,3];sum(l>0)

TypeError: '>' not supported between instances of 'list' and 'int'

In [54]:
ord('!')

33

In [55]:
itemgetter(1)

operator.itemgetter(1)

In [56]:
_char="我"
'\u4e00' <= _char <= '\u9fa5'

True

In [57]:
def is_all_chinese(str):
    return all(map(lambda char:'\u4e00' <= char <= '\u9fa5', str))

In [102]:
import inspect
sig=inspect.signature(is_all_chinese)

In [103]:
type(sig.parameters)

mappingproxy

In [106]:
for name,i in sig.parameters.items():
    print("{},{},{}".format(name,i.default,i.kind))

str,<class 'inspect._empty'>,1


In [62]:
is_all_chinese("#我")

False

In [92]:
def func():
    num=itertools.takewhile(lambda x:x<10,itertools.count(0,1))
    yield num
    num1=filter(lambda x:x%2==1,num)
    yield num1

In [91]:
n0=func()
n1=next(n0)
list(n1) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

n2=next(n0)
list(n2) # []

In [100]:
def func():
    num=itertools.takewhile(lambda x:x<10,itertools.count(0,1))
    num1=filter(lambda x:x%2==1,num.copy())
    return num, num1

In [101]:
a,b=func()
print(list(a)) # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
print(list(b)) # []

AttributeError: 'itertools.takewhile' object has no attribute 'copy'

In [79]:
it=iter(my_iterator) # 相当于 it=iter(iter([1, 2])), 而iter(iter([1, 2]))其实就是iter([1, 2])
while True:
    try:
        print(next(it)**2)
    except:
        break

1
4


In [85]:
from collections import abc

isinstance(range(10),abc.Iterator) # False
isinstance(filter(lambda x:x>=0,_t),abc.Iterator) # True
isinstance(map(lambda x:x>=0,_t),abc.Iterator) # True

In [107]:
a=["abc","anc"]
for i in a:
    i=i.upper()

In [109]:
Point=namedtuple("Point","x y")

In [110]:
a=[Point(3,1),Point(2,2)]
for i in a:
    i.x=3

AttributeError: can't set attribute

In [111]:
import jieba.posseg as pseg

In [116]:
list(pseg.cut("我 以 ,为他 说"))

[pair('我', 'r'),
 pair(' ', 'x'),
 pair('以', 'p'),
 pair(' ', 'x'),
 pair(',', 'x'),
 pair('为', 'p'),
 pair('他', 'r'),
 pair(' ', 'x'),
 pair('说', 'v')]

In [ ]:
word=set([]'','')

In [117]:
?dict.fromkeys

Signature: dict.fromkeys(iterable, value=None, /)
Docstring: Create a new dictionary with keys from iterable and values set to value.
Type:      builtin_function_or_method


In [119]:
?zip

Init signature: zip(self, /, *args, **kwargs)
Docstring:     
zip(iter1 [,iter2 [...]]) --> zip object

Return a zip object whose .__next__() method returns a tuple where
the i-th element comes from the i-th iterable argument.  The .__next__()
method continues until the shortest iterable in the argument sequence
is exhausted and then it raises StopIteration.
Type:           type
Subclasses:     


In [123]:
def word2num(doc_list):
    '''
    接受双层iterable, 展开以后长这样[['我','喜欢'],['但','我','不喜欢']]
    '''
    # word_list
    # 首先需要一个词表
    word_set=set(itertools.chain.from_iterable(doc_list))
    word_num=enumerate(word_set)
    #  词到数的映射
    num2word = dict(word_num)
    word2num=dict(zip(num2word.values(),num2word.keys()))
    print(num2word)
    print(word2num)
    print([list(map(lambda x:word2num[x], doc)) for doc in doc_list])

In [124]:
word2num([['我','喜欢'],['但','我','不喜欢']])

{0: '不喜欢', 1: '我', 2: '但', 3: '喜欢'}
{'不喜欢': 0, '我': 1, '但': 2, '喜欢': 3}
[[1, 3], [2, 1, 0]]


In [126]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [222]:
def build_word_cooccurence_matrix(n,doc_list_in_num,window=2):
    '''接受的已经是一个数的列表
    n表示总的状态数
    '''
    matrix_size = n
    word_matrix=np.zeros((matrix_size,matrix_size))
    for doc in doc_list_in_num:
        for i in range(len(doc)-1):
            for j in range(i+1,min(i+1+window,len(doc))):
                word_matrix[min(doc[i],doc[j]),max(doc[i],doc[j])]+=1
    word_matrix=np.maximum(word_matrix,word_matrix.T)
    return word_matrix

In [223]:
doc_matrix=build_word_cooccurence_matrix(5,[[0,1,2,3,4],[3,1,2,4],[4,0,1]])

doc_matrix
# array([[ 0.000,  1.000,  1.000,  0.000,  1.000],
#        [ 1.000,  0.000,  2.000,  2.000,  2.000],
#        [ 1.000,  2.000,  0.000,  2.000,  1.000],
#        [ 0.000,  2.000,  2.000,  0.000,  0.000],
#        [ 1.000,  2.000,  1.000,  0.000,  0.000]])

array([[ 0.000,  2.000,  1.000,  0.000,  1.000],
       [ 2.000,  0.000,  2.000,  2.000,  2.000],
       [ 1.000,  2.000,  0.000,  2.000,  2.000],
       [ 0.000,  2.000,  2.000,  0.000,  1.000],
       [ 1.000,  2.000,  2.000,  1.000,  0.000]])

In [198]:


where=np.argwhere(res>0)
num=[res[tuple(i)] for i in where if i[0]<i[1]]
for w,n in zip(where,num):
    print("{}:{}".format(w,n))

[1 2]:1.0
[1 3]:3.0
[1 5]:1.0
[1 7]:2.0
[2 1]:2.0
[2 3]:1.0
[2 4]:2.0
[2 5]:1.0
[2 7]:1.0
[2 9]:1.0
[3 1]:2.0
[3 2]:1.0
[3 5]:1.0
[3 7]:1.0
[3 9]:1.0
[4 2]:1.0


In [181]:
a=np.random.randint(0,5,(3,3))

In [182]:
a

array([[1, 3, 3],
       [1, 2, 0],
       [2, 3, 2]])

In [193]:
a/(np.sum(a,axis=1)[:,np.newaxis])

array([[0.14285714, 0.42857143, 0.42857143],
       [0.33333333, 0.66666667, 0.        ],
       [0.28571429, 0.42857143, 0.28571429]])

In [189]:
np.sum(a,axis=1)[:np.newaxis]

array([7, 3, 7])

In [180]:
# a[:,np.all(a==0,axis=0)]=1
# %timeit a[:,np.all(a==0,axis=0)]=1
# %timeit a[:,np.sum(a,axis=0)==0]=1 # 慢

In [195]:
a=a/np.arange(1,4)

In [196]:
a.shape

(3, 3)

In [200]:
def convert2pagerank_matrix(matrix,rsp=0.15):
    '''
    通用方法, 将一个不规则的matrix(必须是方阵), 这个matrix的列可能全为0, 列和也不唯一的转化为pagerank矩阵, 列和为1. 列表示状态的转移概率.
    '''
    n=matrix.shape[0]
    matrix[:,np.all(matrix==0,axis=0)]=1 # 全0列的转换
    matrix=matrix/np.sum(matrix,axis=0) # 单位化
    matrix=matrix*(1-rsp)+rsp/n # 概率
    return matrix

In [221]:
doc_matrix=build_word_cooccurence_matrix(5,[[0,1,2,3,4],[3,1,2,4],[4,0,1]])

doc_matrix
# array([[ 0.000,  1.000,  1.000,  0.000,  1.000],
#        [ 1.000,  0.000,  2.000,  2.000,  2.000],
#        [ 1.000,  2.000,  0.000,  2.000,  1.000],
#        [ 0.000,  2.000,  2.000,  0.000,  0.000],
#        [ 1.000,  2.000,  1.000,  0.000,  0.000]])

In [204]:
import pprint

In [207]:
np.set_printoptions(formatter={'float': '{: 0.3f}'.format})

In [224]:
res=convert2pagerank_matrix(doc_matrix)

In [225]:
res

array([[ 0.030,  0.242,  0.151,  0.030,  0.172],
       [ 0.455,  0.030,  0.273,  0.370,  0.313],
       [ 0.242,  0.242,  0.030,  0.370,  0.313],
       [ 0.030,  0.242,  0.273,  0.030,  0.172],
       [ 0.242,  0.242,  0.273,  0.200,  0.030]])

In [227]:
np.sum(np.ones(3)**2)

3.0

In [228]:
def solve_pagerank_matrix(matrix,tol=1e-6):
    '''
    用幂法解pagerank方程
    '''
    n=matrix.shape[0]
    pr=np.ones(n)
    pr=pr/n
    while True:
        new_pr=matrix@pr
        if(np.sum((new_pr-pr)**2)<tol):
            break
        pr=new_pr
    return pr

In [230]:
sum(solve_pagerank_matrix(res))

0.9999999999999997

In [271]:
import abc

class B:
    @staticmethod
    def my_print(name_="B"):
        print("I'm {}".format(name_))
    def __init__(self):
        self.my_print("yes")
    @staticmethod
    def pretend_print(name_="A"):
        B.my_print(name_)

In [273]:
b=B()

I'm yes


In [274]:
b.pretend_print()

I'm A


In [255]:
assert b.B is not None,"none"

AttributeError: 'B' object has no attribute 'B'

In [280]:
class A:
    a=1
    def __init__(self):
        self.a=2
    def print_a(self):
        print(A.a)

a=A()
a.print_a() # 1

In [281]:
dir(a)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'a',
 'print_a']

In [282]:
class A:
    const=1
    def my_print(const=A.const):
        print(const) # type object 'A' has no attribute 'const'
        
class A:
    const=1
    def my_print(self,const=None):
        print(const or A.const) # type object 'A' has no attribute 'const'

a=A()
a.my_print() # 1

AttributeError: type object 'A' has no attribute 'const'